# Generated by Django 3.0.6 on 2020-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdb',
            name='Done',
            field=models.BooleanField(),
        ),
    ]
