# Generated by Django 3.0.6 on 2020-07-18 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200718_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdb',
            name='Complete',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
