# Generated by Django 3.0 on 2020-07-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20200718_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listdb',
            new_name='Task',
        ),
    ]
