# Generated by Django 3.0 on 2020-07-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200718_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='listdb',
        ),
    ]
